---
- hosts: servers
  vars_files:
    - files/secret/credentials.yaml
  become: yes
  roles:
    - role_upcache
  
- hosts: malikapache
  vars_files:
    - files/secret/credentials.yaml
  become: yes
  roles:
    - role_installation_lamp

- hosts: malikaftp
  vars_files:
    - files/secret/credentials.yaml
  become: yes
  roles:
    - role_installation_haproxy
    - role_installation_ftp