---
# tasks file for role_installation_ftp
- name: instalation de vsftpd pour ftp
  tags: verif
  apt:
    name: vsftpd
    state: present

- name: Create home directory for ftp users
  file: 
    path: /home/dredirect
    state: directory
    mode: 0755

- name: modifier la configuration de ftp 
  tags: titi
  lineinfile:
    dest: "/etc/vsftpd.conf"
    backup: yes
    backrefs: yes
    state: present
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items: "{{ ftp_config }}"


- name: Demarrer vsftpd
  service:
    name: vsftpd
    state: started
    enabled: yes