---
# tasks file for role_installation_lamp
- name: Installation des paquets de LAMP
  tags: toto
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{list_packages}}"

- name: Démarrage de apache mysql et activation au démarrage 
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_list: "{{list_services}}"
    # - apache2
    # - mysql